import Navbar from "../../components/Navbar";
import Head from "next/head";

export const metadata = {
  title: "Kristen's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Agbalumo&family=Dosis:wght@400;700&display=swap"
        />
        {/* Add any other meta tags, title, etc., here */}
      </Head>
      <header>
        <Navbar />
      </header>
      <body className="font-primary">{children}</body>
    </html>
  );
}
